### ISSUE TITLE
Ethers.js throws error when using getBlock() function.

### ISSUE THREAD

**Issue by bcamacho** [celo-org/DevRel#22]
When performing getBlock function with ethers.js a throw error regarding validation occurs.

  reason: 'invalid BigNumber value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: undefined,
  checkKey: 'gasLimit',
  checkValue: undefined

Work around:

It seems the issue is with ethers.js formatter verification. I __commented out__ "throw error" on __line 365__ within @ethersproject/providers/lib/formatter.js to resolve.

I will dig into this some more to figure out a solution to the format validation error regarding gasLimit key. I'm using Ethers v5.3.1.

**Comment by jmrossy** [comment]
The Celo Ethers Wrapper works around this by modifying the block format object:
https://github.com/celo-tools/celo-ethers-wrapper/blob/master/src/lib/CeloProvider.ts#L13
